### ISSUE TITLE
hey! :)

### ISSUE THREAD

**Issue by tenhishadow** [ThePrimeagen/ansible#1]
Hi @ThePrimeagen 

I watch your youtube channel, it's very nice, got this repo by github recommendations
Please take a look on my repos, maybe you could get something from it
( e.g. instead of adding ppa, just use pipenv )

https://github.com/tenhishadow/dotfiles
https://github.com/tenhishadow/ans-workstation

**Comment by tenhishadow** [comment]
as for your content:

```yaml
- name: Install System Packages 3 (the rest)
  apt: name={{item}}
  with_items:
    - curl
    - htop

```
Could be replaced with just:
```yaml
- name: install it
  package:
    name:
      - curl
      - htop
```
