### ISSUE TITLE
Node installation problem

### ISSUE THREAD

**Issue by AndreaGero** [ThePrimeagen/ansible#6]
Hi, I've tried a fresh pop-os installation with this tasks:

```yml
- name: Install NodeJS
  become: true
  apt:
    name: ["nodejs", "npm"]
  tags: &tags_for_node_tasks ["install", "productivity", "node"]

- name: npmjs prefix
  shell: mkdir -p ~/.local/.npm-global
  tags: *tags_for_node_tasks

- name: add npmjs to path
  shell: PATH=~/.local/.npm-global/bin:$PATH
  tags: *tags_for_node_tasks

- name: npmjs global settings
  shell: npm config set prefix '~/.local/.npm-global'
  tags: *tags_for_node_tasks

- name: npmjs global settings export path in case I don't have dotfiles installed
  shell: export PATH=~/.local/.npm-global/bin:$PATH
  tags: *tags_for_node_tasks

- name: Install N
  shell: npm i -g n pnpm
  tags: *tags_for_node_tasks

- name: Install correct version of Node
  shell: n 18
  tags: *tags_for_node_tasks
```

but i think there is a problem with the environment and node global packages, I'm getting the error, `n command not found` while trying to install n 18.

I'm not an expert on Linux, so I don't know how to figure out his issue.

Thanks

**Comment by abdulsalamalmahdi** [comment]
unfortunitly, this was supposed to work out the box since that was the whole point. but there are a lot of problems with persmissions and file owners.

shell command exporting PATH does not persist for following subsequent tasks so an task with `shell: export  var ` won't work.
better specify your ~/.local/.npm-global in vars at the beginning of your playbook
and then 

```
- name: Install correct version of Node
  shell: {{npm_global_dir}}/bin/n 18
  tags:
    - install
    - terminal
    - node 
  ```
